### ISSUE TITLE
Both 'macos-arm64' and 'macos-x86_64' represent two equivalent library definitions.

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-swift#22]
### Description

The following error occured on a simple project
`Both 'macos-arm64' and 'macos-x86_64' represent two equivalent library definitions.`

### Steps to reproduce

created a simple iOS project
added Hedera package
Clicked run

### Hedera network

testnet

### Version

beta

**Comment by mehcode** [comment]
This isn't documented but it appears xcframeworks must use a universal binary for macos support and explicitly must not use them for iOS. The latter is documented so I assumed this held true for mac as well. We'll get this fixed.

You should be able to work around this by only building for active architectures (setting in xcode).

**Comment by ericleponner** [comment]
I enabled `Build Active Architecture Only` for debug and release targets : same error.

I also see another error:
`error: The package product 'NumberKit' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0 (in target 'Hedera' from project 'Hedera')`

I can file a separate issue if it's needed.

**Comment by ericleponner** [comment]
Not sure it's related, but looking at Package.swift in Hedera project, I see a commented line in platforms section:

```
let package = Package(
    name: "Hedera",
    platforms: [
        .macOS(.v10_15)
        // .iOS(.v12),                       <===== HERE
    ],
    products: [
        .library(name: "Hedera", targets: ["Hedera"])
    ],
    dependencies: [
        .package(url: "https://github.com/objecthub/swift-numberkit.git", .upToNextMajor(from: "2.4.1")),
        .package(url: "https://github.com/thebarndog/swift-dotenv.git", .upToNextMajor(from: "1.0.0")),
    ],
    targets: [
        .binaryTarget(name: "CHedera", path: "CHedera.xcframework"),
        .target(name: "Hedera", dependencies: ["CHedera", .product(name: "NumberKit", package: "swift-numberkit")]),
    ] + exampleTargets
)

```

**Comment by ericleponner** [comment]
Cause of this issue could be related to #23 : after fixing Package.swift, everything seems to be build fine.

**Comment by mehcode** [comment]
Fixed in https://github.com/hashgraph/hedera-sdk-rust/pull/204

**Comment by ericleponner** [comment]
This is issue is marked as fixed but it still occurs with 0.6.0 release.
